## Inserting in numpy

In [5]:
"""
We can either use python list or tuple to insert elements in a numpy array

"""

import numpy as np
elements = [1,2,3,4,5,5]
elements2 = [
    [1,2,3,4],
    [5,3,6,7],
    [8,9,1,3]
]
elements3 = (1,2,3,4,5,6)
elements4 = (
    (1,2,3,4),
    (1,6,8,3),
    (4,2,8,7)
)

#creating numpy array
arr_with_1d_list = np.array(elements)
arr_with_2d_list = np.array(elements2)
arr_with_1d_tuple = np.array(elements3)
arr_with_2d_tuple = np.array(elements4)


#printing the numpy array
print("\nArray with 1D list : \n",arr_with_1d_list)
print("\nArray with 2D list : \n",arr_with_2d_list)
print("\nArray with 1D tuple : \n",arr_with_1d_tuple)
print("\nArray with 2D Tuple : \n",arr_with_2d_tuple)


Array with 1D list : 
 [1 2 3 4 5 5]

Array with 2D list : 
 [[1 2 3 4]
 [5 3 6 7]
 [8 9 1 3]]

Array with 1D tuple : 
 [1 2 3 4 5 6]

Array with 2D Tuple : 
 [[1 2 3 4]
 [1 6 8 3]
 [4 2 8 7]]


## Accessing the elements inside of the array

In [22]:
"""
Let's consider the above arr_with_2d_list for further learning
"""

#printing a range of array
print("\nArray with first 2 rows and first 2 columns : \n",arr_with_2d_list[:2,:2])
print("\nArray with first 2 rows and last 2 columns : \n",arr_with_2d_list[:2,-2:])
print("\nArray with first 2 rows and Alternate columns of the first two rows : \n",arr_with_2d_list[:2,::2])


Array with first 2 rows and first 2 columns : 
 [[1 2]
 [5 3]]

Array with first 2 rows and last 2 columns : 
 [[3 4]
 [6 7]]

Array with first 2 rows and Alternate columns of the first two rows : 
 [[1 3]
 [5 6]]


## Basic operations with numpy arrays


In [40]:
#adding a constant value to ana array
arr = np.array([
    [1,2,3,4,5],
    [3,4,5,6,34],
    [7,8,9,4,80],
    [1,2,8,9,100]
])
arr2 = np.array([
    [1,2,3,4],
    [3,4,5,6],
    [7,8,9,4],
    [2,13,4,25]
])

print("\nOriginal Array : \n",arr)
print("\nAdding 2 to all the elements of the 2d array : \n",arr+2)
print("\nSubtracting two from all the elements of the 2d array : \n",arr-2)

#adding two arrays
if(arr.shape == arr2.shape):
    print("\nAdding two arrays : \n",arr+arr2)
else:
    print("\nArray shape must be same.\n")
    
#size of the array = total no. of elements inside the array
print("\n")
print("Total no. of elements : ",arr.size)
print("\nsize of the first dimension",len(arr))


Original Array : 
 [[  1   2   3   4   5]
 [  3   4   5   6  34]
 [  7   8   9   4  80]
 [  1   2   8   9 100]]

Adding 2 to all the elements of the 2d array : 
 [[  3   4   5   6   7]
 [  5   6   7   8  36]
 [  9  10  11   6  82]
 [  3   4  10  11 102]]

Subtracting two from all the elements of the 2d array : 
 [[-1  0  1  2  3]
 [ 1  2  3  4 32]
 [ 5  6  7  2 78]
 [-1  0  6  7 98]]

Array shape must be same.



Total no. of elements :  20

size of the first dimension 5
